#ifndef SIPLASPLAS_LIBCLANG_EXAMPLES_SIMPLE_CLASS_HPP
#define SIPLASPLAS_LIBCLANG_EXAMPLES_SIMPLE_CLASS_HPP

#define SIPLASPLAS_ENABLE_REFLECTION struct EnableReflection {};

class MyClass
{
    SIPLASPLAS_ENABLE_REFLECTION

    void MyMethod() const;
    int foo;
};

#endif // SIPLASPLAS_LIBCLANG_EXAMPLES_SIMPLE_CLASS_HPP
