#ifndef SIPLASPLAS_REFLECTION_STATIC_STATIC_REFLECTION_HPP
#define SIPLASPLAS_REFLECTION_STATIC_STATIC_REFLECTION_HPP

#include "astinfo.hpp"
#include "function.hpp"
#include "field.hpp"

#endif // SIPLASPLAS_REFLECTION_STATIC_STATIC_REFLECTION_HPP
