#ifndef SIPLASPLAS_EXAMPLES_PLUGIN_REFLECTIONRUNTIMELOADER_HPP
#define SIPLASPLAS_EXAMPLES_PLUGIN_REFLECTIONRUNTIMELOADER_HPP

#include <examples/reflection/dynamic/plugin/export.hpp>

extern "C" void PLUGINEXAMPLE_EXPORT SIPLASPLAS_REFLECTION_LOAD_RUNTIME(void* runtimePtr);

#endif // SIPLASPLAS_EXAMPLES_PLUGIN_REFLECTIONRUNTIMELOADER_HPP
