
set(CPACK_PACKAGE_NAME "siplasplas")
set(CPACK_PACKAGE_VENDOR "Manu Sánchez")
set(CPACK_PACKAGE_DESCRIPTION "Examples and utilities for the Advanced C++ course for the GUEIM association, Complutense University of Madrid")
set(CPACK_PACKAGE_VERSION_MAJOR ${SIPLASPLAS_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${SIPLASPLAS_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${SIPLASPLAS_VERSION_PATCH})
set(CPACK_PACKAGE_VERSION "${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}")
set(CPACK_INSTALL_DIRECTORY "siplasplas/v${CPACK_PACKAGE_VERSION}")
set(CPACK_COMPONENTS_ALL libraries headers examples tools)

if(WIN32)
    set(CPACK_GENERATOR NSIS ZIP)
else()
    set(CPACK_GENERATOR TGZ STGZ ZIP)
endif()

include(CPack)
