#ifndef SIPLASPLAS_CONSTEXPR_ASSER_HPP
#define SIPLASPLAS_CONSTEXPR_ASSER_HPP

#include <siplasplas/utility/assert.hpp>

/*
 * Define runtime checks, both Google Test and siplasplas
 * assert can be used:
 */

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_EQ
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_EQ EXPECT_EQ
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_EQ SIPLASPLAS_ASSERT_EQ
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_EQ

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_NE
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_NE EXPECT_NE
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_NE SIPLASPLAS_ASSERT_NE
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_NE

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_GT
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_GT EXPECT_GT
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_GT SIPLASPLAS_ASSERT_GT
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_GT

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LT
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LT EXPECT_LT
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LT SIPLASPLAS_ASSERT_LT
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LT

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BE
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BE EXPECT_BE
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BE SIPLASPLAS_ASSERT_BE
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BE

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LE
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LE EXPECT_LE
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LE SIPLASPLAS_ASSERT_LE
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LE

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_TRUE
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGTRUETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_TRUE EXPECT_TRUE
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_TRUE SIPLASPLAS_ASSERT_TRUE
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_TRUE

#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_FALSE
    #ifdef SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGFALSETEST
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_FALSE EXPECT_FALSE
    #else
        #define SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_FALSE SIPLASPLAS_ASSERT_FALSE
    #endif // SIPLASPLAS_CONSTEXPR_ASSERT_USE_GOOGLETEST
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_FALSE


#ifndef SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_CHECKS_ONLY
    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_EQ(expr, expect) \
        SIPLASPLAS_STATICASSERT_EQ(expr, expect);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_EQ(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_NE(expr, expect) \
        SIPLASPLAS_STATICASSERT_NE(expr, expect);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_NE(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_BT(expr, expect) \
        SIPLASPLAS_STATICASSERT_BT(expr, expect);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BT(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_LT(expr, expect) \
        SIPLASPLAS_STATICASSERT_LT(expr, expect);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LT(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_BE(expr, expect) \
        SIPLASPLAS_STATICASSERT_BE(expr, expect);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BE(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_LE(expr, expect) \
        SIPLASPLAS_STATICASSERT_LE(expr, expect);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LE(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_TRUE(expression) \
        SIPLASPLAS_STATICASSERT_TRUE(expression);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_TRUE(expression)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_FALSE(expression) \
        SIPLASPLAS_STATICASSERT_FALSE(expression);               \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_FALSE(expression)
#else
    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_EQ(expr, expect) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_EQ(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_NE(expr, expect) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_NE(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_BT(expr, expect) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BT(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_LT(expr, expect) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LT(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_BE(expr, expect) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_BE(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_LE(expr, expect) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_LE(expr, expect)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_TRUE(expression) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_TRUE(expression)

    #define SIPLASPLAS_CONSTEXPR_ASSERT_EXPECT_FALSE(expression) \
        SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_EXPECT_FALSE(expression)
#endif // SIPLASPLAS_CONSTEXPR_ASSERT_RUNTIME_CHECKS_ONLY

#endif // SIPLASPLAS_CONSTEXPR_ASSER_HPP
