#ifndef SIPLASPLAS_TEST_REFLECTION_PARSER_API_CORE_TESTUTILS_FILES_SIMPLECLASSES_HPP
#define SIPLASPLAS_TEST_REFLECTION_PARSER_API_CORE_TESTUTILS_FILES_SIMPLECLASSES_HPP

class Foo
{
public:
    void method();
    void methodConst() const;

    static void foo(const char* str);
};

#endif // SIPLASPLAS_TEST_REFLECTION_PARSER_API_CORE_TESTUTILS_FILES_SIMPLECLASSES_HPP
